
WITH novos(numero, nome, frequencia_hz, chakra_alvo, descricao) AS (
  VALUES
    (1,'Purificação Áurica',741,'Laríngeo','Limpeza profunda de miasmas, formas-pensamento negativas e toxinas energéticas do campo sutil.'),
    (2,'Ancoragem Multidimensional',174,'Básico','Redução de dor física e estabelecimento de conexão segura com a malha magnética da Terra.'),
    (3,'Regeneração de DNA e Amor',528,'Cardíaco','Reparo celular, ativação da frequência do amor e harmonização biológica profunda.'),
    (4,'Desconexão de Cordões Energéticos',417,'Sacral','Facilitação de mudanças, limpeza de traumas passados e rompimento de laços obsessivos.'),
    (5,'Alinhamento de Chakras',639,'Cardíaco','Promoção de harmonia em relacionamentos e equilíbrio entre os centros de força.'),
    (6,'Expansão da Consciência',963,'Coronário','Conexão com a unidade cósmica e ativação do estado de presença plena.'),
    (7,'Transmutação de Medos',396,'Básico','Libertação de culpa e medo, transformando bloqueios em realização.'),
    (8,'Intuição e Clarividência',852,'Terceiro Olho','Despertar da visão interior e retorno à ordem espiritual.'),
    (9,'Equilíbrio do Plexo Solar',528,'Plexo Solar','Fortalecimento do poder pessoal, vontade e metabolismo.'),
    (10,'Selagem Energética',741,'Laríngeo','Proteção do campo áurico contra influências externas e drenagem energética.'),
    (11,'Harmonização Laríngea',741,'Laríngeo','Melhora da comunicação e expressão da verdade pessoal.'),
    (12,'Ativação Pineal',963,'Terceiro Olho','Descalcificação energética da glândula pineal e acesso a estados superiores.'),
    (13,'Limpeza de Miasmas',417,'Sacral','Remoção de registros negativos acumulados no corpo emocional.'),
    (14,'Proteção Noosférica',2693,'Coronário','Blindagem contra poluição eletromagnética e psíquica coletiva.'),
    (15,'Conexão Eu Superior',852,'Terceiro Olho','Alinhamento com o propósito de alma e orientação espiritual.'),
    (16,'Cura Emocional Profunda',639,'Cardíaco','Resgate da criança interior e pacificação de conflitos internos.'),
    (17,'Vitalidade Física',285,'Básico','Aceleração da cicatrização e restauração de tecidos e órgãos.'),
    (18,'Clareza Mental',528,'Plexo Solar','Redução de névoa mental e otimização do foco cognitivo.'),
    (19,'Despertar Espiritual',963,'Coronário','Iniciação em novos ciclos de evolução e percepção sutil.'),
    (20,'Sincronia Schumann',7.83,'Básico','Alinhamento com o pulso da Terra para redução de estresse e jet lag.'),
    (21,'Resgate de Alma',417,'Sacral','Reintegração de fragmentos energéticos perdidos em traumas.'),
    (22,'Equilíbrio Yin Yang',639,'Cardíaco','Harmonização das polaridades masculina e feminina no ser.'),
    (23,'Liberação de Traumas Ancestrais',396,'Básico','Limpeza de padrões hereditários limitantes e carmas familiares.'),
    (24,'Fluxo de Abundância',528,'Plexo Solar','Desbloqueio da prosperidade e fluxo criativo na matéria.'),
    (25,'Proteção Psíquica',741,'Laríngeo','Escudo contra ataques psíquicos e vampirismo energético.'),
    (26,'Alinhamento Estelar',963,'Coronário','Sintonização com frequências de origem cósmica e sabedoria superior.'),
    (27,'Cura Ancestral',174,'Básico','Pacificação de linhagens e cura de feridas geracionais.'),
    (28,'Reintegração Energética',285,'Básico','Reestruturação do corpo etérico após cirurgias ou choques.'),
    (29,'Ativação do Timo',639,'Cardíaco','Fortalecimento do sistema imunológico e da alegria de viver.'),
    (30,'Paz Interior',528,'Cardíaco','Estabilização emocional e silenciamento do ruído mental.'),
    (31,'Foco e Concentração',852,'Terceiro Olho','Direcionamento da energia mental para objetivos específicos.'),
    (32,'Criatividade Plena',417,'Sacral','Desbloqueio da expressão artística e soluções inovadoras.'),
    (33,'Autoestima e Valor',528,'Plexo Solar','Reconhecimento do valor intrínseco e amor próprio.'),
    (34,'Perdão e Libertação',639,'Cardíaco','Soltura de mágoas e ressentimentos profundos.'),
    (35,'Conexão com a Terra',174,'Básico','Estabilização em momentos de crise e aterramento.'),
    (36,'Geometria Sagrada',963,'Coronário','Reordenação dos padrões geométricos do corpo de luz.'),
    (37,'Luz e Proteção',741,'Laríngeo','Invocação de frequências de alta vibração para blindagem.'),
    (38,'Equilíbrio Endócrino',528,'Plexo Solar','Harmonização das glândulas e regulação hormonal energética.'),
    (39,'Regeneração Celular',285,'Básico','Estímulo à renovação das células e rejuvenescimento.'),
    (40,'Harmonia Familiar',639,'Cardíaco','Pacificação de ambientes domésticos e laços de sangue.'),
    (41,'Propósito de Vida',852,'Terceiro Olho','Clareza sobre a missão de vida e talentos latentes.'),
    (42,'Gratidão Infinita',528,'Cardíaco','Elevação da frequência para o estado de graça e abundância.'),
    (43,'Unidade Cósmica',963,'Coronário','Integração final com a Fonte e dissolução da dualidade.')
)
UPDATE public.pleitos p
SET nome = n.nome,
    frequencia_hz = n.frequencia_hz,
    chakra_alvo = n.chakra_alvo,
    descricao = n.descricao
FROM novos n
WHERE p.numero = n.numero;

INSERT INTO public.pleitos (numero, nome, frequencia_hz, chakra_alvo, descricao)
SELECT n.numero, n.nome, n.frequencia_hz, n.chakra_alvo, n.descricao
FROM (VALUES
    (1,'Purificação Áurica',741::numeric,'Laríngeo','Limpeza profunda de miasmas, formas-pensamento negativas e toxinas energéticas do campo sutil.'),
    (2,'Ancoragem Multidimensional',174,'Básico','Redução de dor física e estabelecimento de conexão segura com a malha magnética da Terra.'),
    (3,'Regeneração de DNA e Amor',528,'Cardíaco','Reparo celular, ativação da frequência do amor e harmonização biológica profunda.'),
    (4,'Desconexão de Cordões Energéticos',417,'Sacral','Facilitação de mudanças, limpeza de traumas passados e rompimento de laços obsessivos.'),
    (5,'Alinhamento de Chakras',639,'Cardíaco','Promoção de harmonia em relacionamentos e equilíbrio entre os centros de força.'),
    (6,'Expansão da Consciência',963,'Coronário','Conexão com a unidade cósmica e ativação do estado de presença plena.'),
    (7,'Transmutação de Medos',396,'Básico','Libertação de culpa e medo, transformando bloqueios em realização.'),
    (8,'Intuição e Clarividência',852,'Terceiro Olho','Despertar da visão interior e retorno à ordem espiritual.'),
    (9,'Equilíbrio do Plexo Solar',528,'Plexo Solar','Fortalecimento do poder pessoal, vontade e metabolismo.'),
    (10,'Selagem Energética',741,'Laríngeo','Proteção do campo áurico contra influências externas e drenagem energética.'),
    (11,'Harmonização Laríngea',741,'Laríngeo','Melhora da comunicação e expressão da verdade pessoal.'),
    (12,'Ativação Pineal',963,'Terceiro Olho','Descalcificação energética da glândula pineal e acesso a estados superiores.'),
    (13,'Limpeza de Miasmas',417,'Sacral','Remoção de registros negativos acumulados no corpo emocional.'),
    (14,'Proteção Noosférica',2693,'Coronário','Blindagem contra poluição eletromagnética e psíquica coletiva.'),
    (15,'Conexão Eu Superior',852,'Terceiro Olho','Alinhamento com o propósito de alma e orientação espiritual.'),
    (16,'Cura Emocional Profunda',639,'Cardíaco','Resgate da criança interior e pacificação de conflitos internos.'),
    (17,'Vitalidade Física',285,'Básico','Aceleração da cicatrização e restauração de tecidos e órgãos.'),
    (18,'Clareza Mental',528,'Plexo Solar','Redução de névoa mental e otimização do foco cognitivo.'),
    (19,'Despertar Espiritual',963,'Coronário','Iniciação em novos ciclos de evolução e percepção sutil.'),
    (20,'Sincronia Schumann',7.83,'Básico','Alinhamento com o pulso da Terra para redução de estresse e jet lag.'),
    (21,'Resgate de Alma',417,'Sacral','Reintegração de fragmentos energéticos perdidos em traumas.'),
    (22,'Equilíbrio Yin Yang',639,'Cardíaco','Harmonização das polaridades masculina e feminina no ser.'),
    (23,'Liberação de Traumas Ancestrais',396,'Básico','Limpeza de padrões hereditários limitantes e carmas familiares.'),
    (24,'Fluxo de Abundância',528,'Plexo Solar','Desbloqueio da prosperidade e fluxo criativo na matéria.'),
    (25,'Proteção Psíquica',741,'Laríngeo','Escudo contra ataques psíquicos e vampirismo energético.'),
    (26,'Alinhamento Estelar',963,'Coronário','Sintonização com frequências de origem cósmica e sabedoria superior.'),
    (27,'Cura Ancestral',174,'Básico','Pacificação de linhagens e cura de feridas geracionais.'),
    (28,'Reintegração Energética',285,'Básico','Reestruturação do corpo etérico após cirurgias ou choques.'),
    (29,'Ativação do Timo',639,'Cardíaco','Fortalecimento do sistema imunológico e da alegria de viver.'),
    (30,'Paz Interior',528,'Cardíaco','Estabilização emocional e silenciamento do ruído mental.'),
    (31,'Foco e Concentração',852,'Terceiro Olho','Direcionamento da energia mental para objetivos específicos.'),
    (32,'Criatividade Plena',417,'Sacral','Desbloqueio da expressão artística e soluções inovadoras.'),
    (33,'Autoestima e Valor',528,'Plexo Solar','Reconhecimento do valor intrínseco e amor próprio.'),
    (34,'Perdão e Libertação',639,'Cardíaco','Soltura de mágoas e ressentimentos profundos.'),
    (35,'Conexão com a Terra',174,'Básico','Estabilização em momentos de crise e aterramento.'),
    (36,'Geometria Sagrada',963,'Coronário','Reordenação dos padrões geométricos do corpo de luz.'),
    (37,'Luz e Proteção',741,'Laríngeo','Invocação de frequências de alta vibração para blindagem.'),
    (38,'Equilíbrio Endócrino',528,'Plexo Solar','Harmonização das glândulas e regulação hormonal energética.'),
    (39,'Regeneração Celular',285,'Básico','Estímulo à renovação das células e rejuvenescimento.'),
    (40,'Harmonia Familiar',639,'Cardíaco','Pacificação de ambientes domésticos e laços de sangue.'),
    (41,'Propósito de Vida',852,'Terceiro Olho','Clareza sobre a missão de vida e talentos latentes.'),
    (42,'Gratidão Infinita',528,'Cardíaco','Elevação da frequência para o estado de graça e abundância.'),
    (43,'Unidade Cósmica',963,'Coronário','Integração final com a Fonte e dissolução da dualidade.')
) AS n(numero,nome,frequencia_hz,chakra_alvo,descricao)
WHERE NOT EXISTS (SELECT 1 FROM public.pleitos p WHERE p.numero = n.numero);
