/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UmbilicalRouteImport } from './routes/umbilical'
import { Route as TocadorRouteImport } from './routes/tocador'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as PhysicalPhotoRouteImport } from './routes/physical-photo'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as NoosphericRouteImport } from './routes/noospheric'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GriefRouteImport } from './routes/grief'
import { Route as FrequenciesRouteImport } from './routes/frequencies'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuraColorsRouteImport } from './routes/aura-colors'
import { Route as AuraByNameRouteImport } from './routes/aura-by-name'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionPatientIdRouteImport } from './routes/session.$patientId'
import { Route as PatientPatientIdRouteImport } from './routes/patient.$patientId'

const UmbilicalRoute = UmbilicalRouteImport.update({
  id: '/umbilical',
  path: '/umbilical',
  getParentRoute: () => rootRouteImport,
} as any)
const TocadorRoute = TocadorRouteImport.update({
  id: '/tocador',
  path: '/tocador',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalPhotoRoute = PhysicalPhotoRouteImport.update({
  id: '/physical-photo',
  path: '/physical-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const NoosphericRoute = NoosphericRouteImport.update({
  id: '/noospheric',
  path: '/noospheric',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GriefRoute = GriefRouteImport.update({
  id: '/grief',
  path: '/grief',
  getParentRoute: () => rootRouteImport,
} as any)
const FrequenciesRoute = FrequenciesRouteImport.update({
  id: '/frequencies',
  path: '/frequencies',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraColorsRoute = AuraColorsRouteImport.update({
  id: '/aura-colors',
  path: '/aura-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraByNameRoute = AuraByNameRouteImport.update({
  id: '/aura-by-name',
  path: '/aura-by-name',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionPatientIdRoute = SessionPatientIdRouteImport.update({
  id: '/session/$patientId',
  path: '/session/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPatientIdRoute = PatientPatientIdRouteImport.update({
  id: '/patient/$patientId',
  path: '/patient/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aura-by-name': typeof AuraByNameRoute
  '/aura-colors': typeof AuraColorsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/frequencies': typeof FrequenciesRoute
  '/grief': typeof GriefRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/noospheric': typeof NoosphericRoute
  '/patients': typeof PatientsRoute
  '/physical-photo': typeof PhysicalPhotoRoute
  '/protocol': typeof ProtocolRoute
  '/report': typeof ReportRoute
  '/tocador': typeof TocadorRoute
  '/umbilical': typeof UmbilicalRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/session/$patientId': typeof SessionPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aura-by-name': typeof AuraByNameRoute
  '/aura-colors': typeof AuraColorsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/frequencies': typeof FrequenciesRoute
  '/grief': typeof GriefRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/noospheric': typeof NoosphericRoute
  '/patients': typeof PatientsRoute
  '/physical-photo': typeof PhysicalPhotoRoute
  '/protocol': typeof ProtocolRoute
  '/report': typeof ReportRoute
  '/tocador': typeof TocadorRoute
  '/umbilical': typeof UmbilicalRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/session/$patientId': typeof SessionPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aura-by-name': typeof AuraByNameRoute
  '/aura-colors': typeof AuraColorsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/frequencies': typeof FrequenciesRoute
  '/grief': typeof GriefRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/noospheric': typeof NoosphericRoute
  '/patients': typeof PatientsRoute
  '/physical-photo': typeof PhysicalPhotoRoute
  '/protocol': typeof ProtocolRoute
  '/report': typeof ReportRoute
  '/tocador': typeof TocadorRoute
  '/umbilical': typeof UmbilicalRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/session/$patientId': typeof SessionPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aura-by-name'
    | '/aura-colors'
    | '/dashboard'
    | '/docs'
    | '/frequencies'
    | '/grief'
    | '/history'
    | '/login'
    | '/noospheric'
    | '/patients'
    | '/physical-photo'
    | '/protocol'
    | '/report'
    | '/tocador'
    | '/umbilical'
    | '/patient/$patientId'
    | '/session/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aura-by-name'
    | '/aura-colors'
    | '/dashboard'
    | '/docs'
    | '/frequencies'
    | '/grief'
    | '/history'
    | '/login'
    | '/noospheric'
    | '/patients'
    | '/physical-photo'
    | '/protocol'
    | '/report'
    | '/tocador'
    | '/umbilical'
    | '/patient/$patientId'
    | '/session/$patientId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aura-by-name'
    | '/aura-colors'
    | '/dashboard'
    | '/docs'
    | '/frequencies'
    | '/grief'
    | '/history'
    | '/login'
    | '/noospheric'
    | '/patients'
    | '/physical-photo'
    | '/protocol'
    | '/report'
    | '/tocador'
    | '/umbilical'
    | '/patient/$patientId'
    | '/session/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuraByNameRoute: typeof AuraByNameRoute
  AuraColorsRoute: typeof AuraColorsRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  FrequenciesRoute: typeof FrequenciesRoute
  GriefRoute: typeof GriefRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NoosphericRoute: typeof NoosphericRoute
  PatientsRoute: typeof PatientsRoute
  PhysicalPhotoRoute: typeof PhysicalPhotoRoute
  ProtocolRoute: typeof ProtocolRoute
  ReportRoute: typeof ReportRoute
  TocadorRoute: typeof TocadorRoute
  UmbilicalRoute: typeof UmbilicalRoute
  PatientPatientIdRoute: typeof PatientPatientIdRoute
  SessionPatientIdRoute: typeof SessionPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/umbilical': {
      id: '/umbilical'
      path: '/umbilical'
      fullPath: '/umbilical'
      preLoaderRoute: typeof UmbilicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tocador': {
      id: '/tocador'
      path: '/tocador'
      fullPath: '/tocador'
      preLoaderRoute: typeof TocadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-photo': {
      id: '/physical-photo'
      path: '/physical-photo'
      fullPath: '/physical-photo'
      preLoaderRoute: typeof PhysicalPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noospheric': {
      id: '/noospheric'
      path: '/noospheric'
      fullPath: '/noospheric'
      preLoaderRoute: typeof NoosphericRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grief': {
      id: '/grief'
      path: '/grief'
      fullPath: '/grief'
      preLoaderRoute: typeof GriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frequencies': {
      id: '/frequencies'
      path: '/frequencies'
      fullPath: '/frequencies'
      preLoaderRoute: typeof FrequenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura-colors': {
      id: '/aura-colors'
      path: '/aura-colors'
      fullPath: '/aura-colors'
      preLoaderRoute: typeof AuraColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura-by-name': {
      id: '/aura-by-name'
      path: '/aura-by-name'
      fullPath: '/aura-by-name'
      preLoaderRoute: typeof AuraByNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$patientId': {
      id: '/session/$patientId'
      path: '/session/$patientId'
      fullPath: '/session/$patientId'
      preLoaderRoute: typeof SessionPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$patientId': {
      id: '/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof PatientPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuraByNameRoute: AuraByNameRoute,
  AuraColorsRoute: AuraColorsRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  FrequenciesRoute: FrequenciesRoute,
  GriefRoute: GriefRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NoosphericRoute: NoosphericRoute,
  PatientsRoute: PatientsRoute,
  PhysicalPhotoRoute: PhysicalPhotoRoute,
  ProtocolRoute: ProtocolRoute,
  ReportRoute: ReportRoute,
  TocadorRoute: TocadorRoute,
  UmbilicalRoute: UmbilicalRoute,
  PatientPatientIdRoute: PatientPatientIdRoute,
  SessionPatientIdRoute: SessionPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
